@startuml
'!pragma layout smetana
skinparam classAttributeIconSize 0
class Pedido {
  +numero: int
  +data: String
}
class ItemPedido {
  +quantidade: int
  +calcularSubtotal(): double
}
Pedido *-- ItemPedido
@endumlD